version: '3.5'
services:
  adminer:
    image: adminer
    restart: always
    ports:
    - "8080:8080"
#   redis:
#     image: redis:5.0.5
#     command: redis-server --requirepass redispassword
#     volumes:
#     - redis-data:/data
#     ports:
#     - "6379:6379"
  # minio:
  #   command: '--compat server --address ":9001" /data'
  #   environment:
  #     CREATE_BUCKET: shrine
  #     MINIO_ACCESS_KEY: foobarfoobar
  #     MINIO_SECRET_KEY: foobarfoobar
  #   image: minio/minio:latest
  #   volumes:
  #   - minio:/data
  #   ports:
  #   # my vscode gobbles up port 9000
  #   - "9001:9001"
  dbjson:
    environment:
      POSTGRES_PASSWORD: ssjson
      POSTGRES_USER: ssjson
      POSTGRES_DB: ssjson
    image: postgres:10
    ports:
    - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
  # sidekiq:
  #   env_file: s3.env
  #   environment:
  #     REDIS_HOST: redis
  #     REDIS_PASSWORD: redispassword
  #     RAILS_SERVE_STATIC_FILES: "true"
  #     RAILS_ENV: development
  #     RAILS_LOG_TO_STDOUT: "true"
  #     POSTGRES_USER: shrinedemo
  #     POSTGRES_HOST: db
  #     POSTGRES_DB: shrinedemo
  #     POSTGRES_PASSWORD: shrinedemo
  #   build: .
  #   command: >
  #     sh -c "bundle exec sidekiq"
  # webjson:
  #   # env_file: s3.env
  #   ttyj:
    # - dbjson

volumes:
  redis-data:
  minio:
  db-data:

networks:
  ss-json_default:
  psu-authproxy_default:
    external: true